#!/bin/bash
cd deb-files
sudo dpkg -i code_1.52.1-1608136922_amd64.deb
echo "Installing vsc. The deb-files directory also contains a file for teams,to install the command is sudo dpkg teams_1.3.00.30857_amd64.deb" 
cd
mdkir bash
echo 'git add\ngit commit -m "$1"\ngit push' > ~/bash/push 
echo export PATH="$HOME/bash:$PATH"  > ~/.zshrc
cd bash
chmod +x push
echo "TESTING PUSH"
push "int"
cd 
sudo apt-get install git
echo "GIT INSTALLED"
git config --global user.name "lolmokha"
git config --global user.email "mkhan0138@gmail.com"
sudo apt install tilix
echo "TILIX INSTALLED"
sudo apt install ffmpeg
echo "FFMPEG INSTALLED"
pip3 install spot-dl
echo "SPOT-DL INSTALLED"
echo "syntax on\nset wrapmargin=8\nset number" > ~/.vimrc
echo "VIMRC INITIALIZED"
echo "THATS IT FOR NOW"
